/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuukodus;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Edgar
 */
public class SudokuVista extends javax.swing.JFrame {
    private JTextField[][] matrizT;
    private int[][] matriz;
    private Timer timer;
    private int counter;
    private int ii;
    private int jj;

    /**
     * Creates new form SudokuVista
     */
    public SudokuVista() {
        initComponents();
        matrizT = new JTextField[9][9];
        matriz= new int[9][9];
        creaMatriz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        S = new javax.swing.JLayeredPane();
        s1 = new javax.swing.JLayeredPane();
        s00 = new javax.swing.JTextField();
        s01 = new javax.swing.JTextField();
        s02 = new javax.swing.JTextField();
        s10 = new javax.swing.JTextField();
        s11 = new javax.swing.JTextField();
        s12 = new javax.swing.JTextField();
        s20 = new javax.swing.JTextField();
        s21 = new javax.swing.JTextField();
        s22 = new javax.swing.JTextField();
        s2 = new javax.swing.JLayeredPane();
        s03 = new javax.swing.JTextField();
        s04 = new javax.swing.JTextField();
        s05 = new javax.swing.JTextField();
        s13 = new javax.swing.JTextField();
        s14 = new javax.swing.JTextField();
        s15 = new javax.swing.JTextField();
        s23 = new javax.swing.JTextField();
        s24 = new javax.swing.JTextField();
        s25 = new javax.swing.JTextField();
        s3 = new javax.swing.JLayeredPane();
        s06 = new javax.swing.JTextField();
        s07 = new javax.swing.JTextField();
        s08 = new javax.swing.JTextField();
        s16 = new javax.swing.JTextField();
        s17 = new javax.swing.JTextField();
        s18 = new javax.swing.JTextField();
        s26 = new javax.swing.JTextField();
        s27 = new javax.swing.JTextField();
        s28 = new javax.swing.JTextField();
        s4 = new javax.swing.JLayeredPane();
        s30 = new javax.swing.JTextField();
        s31 = new javax.swing.JTextField();
        s32 = new javax.swing.JTextField();
        s40 = new javax.swing.JTextField();
        s41 = new javax.swing.JTextField();
        s42 = new javax.swing.JTextField();
        s50 = new javax.swing.JTextField();
        s51 = new javax.swing.JTextField();
        s52 = new javax.swing.JTextField();
        s5 = new javax.swing.JLayeredPane();
        s33 = new javax.swing.JTextField();
        s34 = new javax.swing.JTextField();
        s35 = new javax.swing.JTextField();
        s43 = new javax.swing.JTextField();
        s44 = new javax.swing.JTextField();
        s45 = new javax.swing.JTextField();
        s53 = new javax.swing.JTextField();
        s54 = new javax.swing.JTextField();
        s55 = new javax.swing.JTextField();
        s6 = new javax.swing.JLayeredPane();
        s36 = new javax.swing.JTextField();
        s37 = new javax.swing.JTextField();
        s38 = new javax.swing.JTextField();
        s46 = new javax.swing.JTextField();
        s47 = new javax.swing.JTextField();
        s48 = new javax.swing.JTextField();
        s56 = new javax.swing.JTextField();
        s57 = new javax.swing.JTextField();
        s58 = new javax.swing.JTextField();
        s7 = new javax.swing.JLayeredPane();
        s60 = new javax.swing.JTextField();
        s61 = new javax.swing.JTextField();
        s62 = new javax.swing.JTextField();
        s70 = new javax.swing.JTextField();
        s71 = new javax.swing.JTextField();
        s72 = new javax.swing.JTextField();
        s80 = new javax.swing.JTextField();
        s81 = new javax.swing.JTextField();
        s82 = new javax.swing.JTextField();
        s8 = new javax.swing.JLayeredPane();
        s63 = new javax.swing.JTextField();
        s64 = new javax.swing.JTextField();
        s65 = new javax.swing.JTextField();
        s73 = new javax.swing.JTextField();
        s74 = new javax.swing.JTextField();
        s75 = new javax.swing.JTextField();
        s83 = new javax.swing.JTextField();
        s84 = new javax.swing.JTextField();
        s85 = new javax.swing.JTextField();
        s9 = new javax.swing.JLayeredPane();
        s66 = new javax.swing.JTextField();
        s67 = new javax.swing.JTextField();
        s68 = new javax.swing.JTextField();
        s76 = new javax.swing.JTextField();
        s77 = new javax.swing.JTextField();
        s78 = new javax.swing.JTextField();
        s86 = new javax.swing.JTextField();
        s87 = new javax.swing.JTextField();
        s88 = new javax.swing.JTextField();
        clean = new javax.swing.JLabel();
        solve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("😎 😎 😎 Sudoku Ukodus 😎 😎 😎");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);

        S.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        S.setLayout(new java.awt.GridLayout(3, 3));

        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s1.setPreferredSize(new java.awt.Dimension(150, 150));
        s1.setLayout(new java.awt.GridLayout(3, 3));

        s00.setBackground(new java.awt.Color(0, 0, 0));
        s00.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s00.setForeground(new java.awt.Color(0, 255, 51));
        s00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s00ActionPerformed(evt);
            }
        });
        s1.add(s00);

        s01.setBackground(new java.awt.Color(0, 0, 0));
        s01.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s01.setForeground(new java.awt.Color(0, 255, 51));
        s01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s01ActionPerformed(evt);
            }
        });
        s1.add(s01);

        s02.setBackground(new java.awt.Color(0, 0, 0));
        s02.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s02.setForeground(new java.awt.Color(0, 255, 51));
        s02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s02ActionPerformed(evt);
            }
        });
        s1.add(s02);

        s10.setBackground(new java.awt.Color(0, 0, 0));
        s10.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s10.setForeground(new java.awt.Color(0, 255, 51));
        s10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        s1.add(s10);

        s11.setBackground(new java.awt.Color(0, 0, 0));
        s11.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s11.setForeground(new java.awt.Color(0, 255, 51));
        s11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });
        s1.add(s11);

        s12.setBackground(new java.awt.Color(0, 0, 0));
        s12.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s12.setForeground(new java.awt.Color(0, 255, 51));
        s12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        s1.add(s12);

        s20.setBackground(new java.awt.Color(0, 0, 0));
        s20.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s20.setForeground(new java.awt.Color(0, 255, 51));
        s20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20ActionPerformed(evt);
            }
        });
        s1.add(s20);

        s21.setBackground(new java.awt.Color(0, 0, 0));
        s21.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s21.setForeground(new java.awt.Color(0, 255, 51));
        s21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s21ActionPerformed(evt);
            }
        });
        s1.add(s21);

        s22.setBackground(new java.awt.Color(0, 0, 0));
        s22.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s22.setForeground(new java.awt.Color(0, 255, 51));
        s22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s22ActionPerformed(evt);
            }
        });
        s1.add(s22);

        S.add(s1);

        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s2.setPreferredSize(new java.awt.Dimension(150, 150));
        s2.setLayout(new java.awt.GridLayout(3, 3));

        s03.setBackground(new java.awt.Color(0, 0, 0));
        s03.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s03.setForeground(new java.awt.Color(0, 255, 51));
        s03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s03ActionPerformed(evt);
            }
        });
        s2.add(s03);

        s04.setBackground(new java.awt.Color(0, 0, 0));
        s04.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s04.setForeground(new java.awt.Color(0, 255, 51));
        s04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s04ActionPerformed(evt);
            }
        });
        s2.add(s04);

        s05.setBackground(new java.awt.Color(0, 0, 0));
        s05.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s05.setForeground(new java.awt.Color(0, 255, 51));
        s05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s05ActionPerformed(evt);
            }
        });
        s2.add(s05);

        s13.setBackground(new java.awt.Color(0, 0, 0));
        s13.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s13.setForeground(new java.awt.Color(0, 255, 51));
        s13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s13ActionPerformed(evt);
            }
        });
        s2.add(s13);

        s14.setBackground(new java.awt.Color(0, 0, 0));
        s14.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s14.setForeground(new java.awt.Color(0, 255, 51));
        s14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s14ActionPerformed(evt);
            }
        });
        s2.add(s14);

        s15.setBackground(new java.awt.Color(0, 0, 0));
        s15.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s15.setForeground(new java.awt.Color(0, 255, 51));
        s15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s15ActionPerformed(evt);
            }
        });
        s2.add(s15);

        s23.setBackground(new java.awt.Color(0, 0, 0));
        s23.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s23.setForeground(new java.awt.Color(0, 255, 51));
        s23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s23ActionPerformed(evt);
            }
        });
        s2.add(s23);

        s24.setBackground(new java.awt.Color(0, 0, 0));
        s24.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s24.setForeground(new java.awt.Color(0, 255, 51));
        s24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s24ActionPerformed(evt);
            }
        });
        s2.add(s24);

        s25.setBackground(new java.awt.Color(0, 0, 0));
        s25.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s25.setForeground(new java.awt.Color(0, 255, 51));
        s25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s25ActionPerformed(evt);
            }
        });
        s2.add(s25);

        S.add(s2);

        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s3.setPreferredSize(new java.awt.Dimension(150, 150));
        s3.setLayout(new java.awt.GridLayout(3, 3));

        s06.setBackground(new java.awt.Color(0, 0, 0));
        s06.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s06.setForeground(new java.awt.Color(0, 255, 51));
        s06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s06ActionPerformed(evt);
            }
        });
        s3.add(s06);

        s07.setBackground(new java.awt.Color(0, 0, 0));
        s07.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s07.setForeground(new java.awt.Color(0, 255, 51));
        s07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s07ActionPerformed(evt);
            }
        });
        s3.add(s07);

        s08.setBackground(new java.awt.Color(0, 0, 0));
        s08.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s08.setForeground(new java.awt.Color(0, 255, 51));
        s08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s08ActionPerformed(evt);
            }
        });
        s3.add(s08);

        s16.setBackground(new java.awt.Color(0, 0, 0));
        s16.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s16.setForeground(new java.awt.Color(0, 255, 51));
        s16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s16ActionPerformed(evt);
            }
        });
        s3.add(s16);

        s17.setBackground(new java.awt.Color(0, 0, 0));
        s17.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s17.setForeground(new java.awt.Color(0, 255, 51));
        s17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s17ActionPerformed(evt);
            }
        });
        s3.add(s17);

        s18.setBackground(new java.awt.Color(0, 0, 0));
        s18.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s18.setForeground(new java.awt.Color(0, 255, 51));
        s18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s18ActionPerformed(evt);
            }
        });
        s3.add(s18);

        s26.setBackground(new java.awt.Color(0, 0, 0));
        s26.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s26.setForeground(new java.awt.Color(0, 255, 51));
        s26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s26ActionPerformed(evt);
            }
        });
        s3.add(s26);

        s27.setBackground(new java.awt.Color(0, 0, 0));
        s27.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s27.setForeground(new java.awt.Color(0, 255, 51));
        s27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s27ActionPerformed(evt);
            }
        });
        s3.add(s27);

        s28.setBackground(new java.awt.Color(0, 0, 0));
        s28.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s28.setForeground(new java.awt.Color(0, 255, 51));
        s28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s28ActionPerformed(evt);
            }
        });
        s3.add(s28);

        S.add(s3);

        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s4.setPreferredSize(new java.awt.Dimension(150, 150));
        s4.setLayout(new java.awt.GridLayout(3, 3));

        s30.setBackground(new java.awt.Color(0, 0, 0));
        s30.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s30.setForeground(new java.awt.Color(0, 255, 51));
        s30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s30ActionPerformed(evt);
            }
        });
        s4.add(s30);

        s31.setBackground(new java.awt.Color(0, 0, 0));
        s31.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s31.setForeground(new java.awt.Color(0, 255, 51));
        s31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s31ActionPerformed(evt);
            }
        });
        s4.add(s31);

        s32.setBackground(new java.awt.Color(0, 0, 0));
        s32.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s32.setForeground(new java.awt.Color(0, 255, 51));
        s32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s32ActionPerformed(evt);
            }
        });
        s4.add(s32);

        s40.setBackground(new java.awt.Color(0, 0, 0));
        s40.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s40.setForeground(new java.awt.Color(0, 255, 51));
        s40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s40ActionPerformed(evt);
            }
        });
        s4.add(s40);

        s41.setBackground(new java.awt.Color(0, 0, 0));
        s41.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s41.setForeground(new java.awt.Color(0, 255, 51));
        s41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s41ActionPerformed(evt);
            }
        });
        s4.add(s41);

        s42.setBackground(new java.awt.Color(0, 0, 0));
        s42.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s42.setForeground(new java.awt.Color(0, 255, 51));
        s42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s42ActionPerformed(evt);
            }
        });
        s4.add(s42);

        s50.setBackground(new java.awt.Color(0, 0, 0));
        s50.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s50.setForeground(new java.awt.Color(0, 255, 51));
        s50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s50ActionPerformed(evt);
            }
        });
        s4.add(s50);

        s51.setBackground(new java.awt.Color(0, 0, 0));
        s51.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s51.setForeground(new java.awt.Color(0, 255, 51));
        s51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s51ActionPerformed(evt);
            }
        });
        s4.add(s51);

        s52.setBackground(new java.awt.Color(0, 0, 0));
        s52.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s52.setForeground(new java.awt.Color(0, 255, 51));
        s52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s52ActionPerformed(evt);
            }
        });
        s4.add(s52);

        S.add(s4);

        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s5.setPreferredSize(new java.awt.Dimension(150, 150));
        s5.setLayout(new java.awt.GridLayout(3, 3));

        s33.setBackground(new java.awt.Color(0, 0, 0));
        s33.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s33.setForeground(new java.awt.Color(0, 255, 51));
        s33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s33ActionPerformed(evt);
            }
        });
        s5.add(s33);

        s34.setBackground(new java.awt.Color(0, 0, 0));
        s34.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s34.setForeground(new java.awt.Color(0, 255, 51));
        s34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s34ActionPerformed(evt);
            }
        });
        s5.add(s34);

        s35.setBackground(new java.awt.Color(0, 0, 0));
        s35.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s35.setForeground(new java.awt.Color(0, 255, 51));
        s35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s35ActionPerformed(evt);
            }
        });
        s5.add(s35);

        s43.setBackground(new java.awt.Color(0, 0, 0));
        s43.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s43.setForeground(new java.awt.Color(0, 255, 51));
        s43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s43ActionPerformed(evt);
            }
        });
        s5.add(s43);

        s44.setBackground(new java.awt.Color(0, 0, 0));
        s44.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s44.setForeground(new java.awt.Color(0, 255, 51));
        s44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s44ActionPerformed(evt);
            }
        });
        s5.add(s44);

        s45.setBackground(new java.awt.Color(0, 0, 0));
        s45.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s45.setForeground(new java.awt.Color(0, 255, 51));
        s45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s45ActionPerformed(evt);
            }
        });
        s5.add(s45);

        s53.setBackground(new java.awt.Color(0, 0, 0));
        s53.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s53.setForeground(new java.awt.Color(0, 255, 51));
        s53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s53ActionPerformed(evt);
            }
        });
        s5.add(s53);

        s54.setBackground(new java.awt.Color(0, 0, 0));
        s54.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s54.setForeground(new java.awt.Color(0, 255, 51));
        s54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s54ActionPerformed(evt);
            }
        });
        s5.add(s54);

        s55.setBackground(new java.awt.Color(0, 0, 0));
        s55.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s55.setForeground(new java.awt.Color(0, 255, 51));
        s55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s55ActionPerformed(evt);
            }
        });
        s5.add(s55);

        S.add(s5);

        s6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s6.setPreferredSize(new java.awt.Dimension(150, 150));
        s6.setLayout(new java.awt.GridLayout(3, 3));

        s36.setBackground(new java.awt.Color(0, 0, 0));
        s36.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s36.setForeground(new java.awt.Color(0, 255, 51));
        s36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s36ActionPerformed(evt);
            }
        });
        s6.add(s36);

        s37.setBackground(new java.awt.Color(0, 0, 0));
        s37.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s37.setForeground(new java.awt.Color(0, 255, 51));
        s37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s37ActionPerformed(evt);
            }
        });
        s6.add(s37);

        s38.setBackground(new java.awt.Color(0, 0, 0));
        s38.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s38.setForeground(new java.awt.Color(0, 255, 51));
        s38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s38ActionPerformed(evt);
            }
        });
        s6.add(s38);

        s46.setBackground(new java.awt.Color(0, 0, 0));
        s46.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s46.setForeground(new java.awt.Color(0, 255, 51));
        s46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s46ActionPerformed(evt);
            }
        });
        s6.add(s46);

        s47.setBackground(new java.awt.Color(0, 0, 0));
        s47.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s47.setForeground(new java.awt.Color(0, 255, 51));
        s47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s47ActionPerformed(evt);
            }
        });
        s6.add(s47);

        s48.setBackground(new java.awt.Color(0, 0, 0));
        s48.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s48.setForeground(new java.awt.Color(0, 255, 51));
        s48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s48ActionPerformed(evt);
            }
        });
        s6.add(s48);

        s56.setBackground(new java.awt.Color(0, 0, 0));
        s56.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s56.setForeground(new java.awt.Color(0, 255, 51));
        s56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s56ActionPerformed(evt);
            }
        });
        s6.add(s56);

        s57.setBackground(new java.awt.Color(0, 0, 0));
        s57.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s57.setForeground(new java.awt.Color(0, 255, 51));
        s57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s57ActionPerformed(evt);
            }
        });
        s6.add(s57);

        s58.setBackground(new java.awt.Color(0, 0, 0));
        s58.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s58.setForeground(new java.awt.Color(0, 255, 51));
        s58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s58ActionPerformed(evt);
            }
        });
        s6.add(s58);

        S.add(s6);

        s7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s7.setPreferredSize(new java.awt.Dimension(150, 150));
        s7.setLayout(new java.awt.GridLayout(3, 3));

        s60.setBackground(new java.awt.Color(0, 0, 0));
        s60.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s60.setForeground(new java.awt.Color(0, 255, 51));
        s60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s60ActionPerformed(evt);
            }
        });
        s7.add(s60);

        s61.setBackground(new java.awt.Color(0, 0, 0));
        s61.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s61.setForeground(new java.awt.Color(0, 255, 51));
        s61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s61ActionPerformed(evt);
            }
        });
        s7.add(s61);

        s62.setBackground(new java.awt.Color(0, 0, 0));
        s62.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s62.setForeground(new java.awt.Color(0, 255, 51));
        s62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s62ActionPerformed(evt);
            }
        });
        s7.add(s62);

        s70.setBackground(new java.awt.Color(0, 0, 0));
        s70.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s70.setForeground(new java.awt.Color(0, 255, 51));
        s70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s70ActionPerformed(evt);
            }
        });
        s7.add(s70);

        s71.setBackground(new java.awt.Color(0, 0, 0));
        s71.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s71.setForeground(new java.awt.Color(0, 255, 51));
        s71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s71ActionPerformed(evt);
            }
        });
        s7.add(s71);

        s72.setBackground(new java.awt.Color(0, 0, 0));
        s72.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s72.setForeground(new java.awt.Color(0, 255, 51));
        s72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s72ActionPerformed(evt);
            }
        });
        s7.add(s72);

        s80.setBackground(new java.awt.Color(0, 0, 0));
        s80.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s80.setForeground(new java.awt.Color(0, 255, 51));
        s80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s80ActionPerformed(evt);
            }
        });
        s7.add(s80);

        s81.setBackground(new java.awt.Color(0, 0, 0));
        s81.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s81.setForeground(new java.awt.Color(0, 255, 51));
        s81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s81ActionPerformed(evt);
            }
        });
        s7.add(s81);

        s82.setBackground(new java.awt.Color(0, 0, 0));
        s82.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s82.setForeground(new java.awt.Color(0, 255, 51));
        s82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s82ActionPerformed(evt);
            }
        });
        s7.add(s82);

        S.add(s7);

        s8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s8.setPreferredSize(new java.awt.Dimension(150, 150));
        s8.setLayout(new java.awt.GridLayout(3, 3));

        s63.setBackground(new java.awt.Color(0, 0, 0));
        s63.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s63.setForeground(new java.awt.Color(0, 255, 51));
        s63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s63ActionPerformed(evt);
            }
        });
        s8.add(s63);

        s64.setBackground(new java.awt.Color(0, 0, 0));
        s64.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s64.setForeground(new java.awt.Color(0, 255, 51));
        s64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s64ActionPerformed(evt);
            }
        });
        s8.add(s64);

        s65.setBackground(new java.awt.Color(0, 0, 0));
        s65.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s65.setForeground(new java.awt.Color(0, 255, 51));
        s65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s65ActionPerformed(evt);
            }
        });
        s8.add(s65);

        s73.setBackground(new java.awt.Color(0, 0, 0));
        s73.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s73.setForeground(new java.awt.Color(0, 255, 51));
        s73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s73ActionPerformed(evt);
            }
        });
        s8.add(s73);

        s74.setBackground(new java.awt.Color(0, 0, 0));
        s74.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s74.setForeground(new java.awt.Color(0, 255, 51));
        s74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s74ActionPerformed(evt);
            }
        });
        s8.add(s74);

        s75.setBackground(new java.awt.Color(0, 0, 0));
        s75.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s75.setForeground(new java.awt.Color(0, 255, 51));
        s75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s75ActionPerformed(evt);
            }
        });
        s8.add(s75);

        s83.setBackground(new java.awt.Color(0, 0, 0));
        s83.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s83.setForeground(new java.awt.Color(0, 255, 51));
        s83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s83ActionPerformed(evt);
            }
        });
        s8.add(s83);

        s84.setBackground(new java.awt.Color(0, 0, 0));
        s84.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s84.setForeground(new java.awt.Color(0, 255, 51));
        s84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s84ActionPerformed(evt);
            }
        });
        s8.add(s84);

        s85.setBackground(new java.awt.Color(0, 0, 0));
        s85.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s85.setForeground(new java.awt.Color(0, 255, 51));
        s85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s85ActionPerformed(evt);
            }
        });
        s8.add(s85);

        S.add(s8);

        s9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        s9.setPreferredSize(new java.awt.Dimension(150, 150));
        s9.setLayout(new java.awt.GridLayout(3, 3));

        s66.setBackground(new java.awt.Color(0, 0, 0));
        s66.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s66.setForeground(new java.awt.Color(0, 255, 51));
        s66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s66ActionPerformed(evt);
            }
        });
        s9.add(s66);

        s67.setBackground(new java.awt.Color(0, 0, 0));
        s67.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s67.setForeground(new java.awt.Color(0, 255, 51));
        s67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s67ActionPerformed(evt);
            }
        });
        s9.add(s67);

        s68.setBackground(new java.awt.Color(0, 0, 0));
        s68.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s68.setForeground(new java.awt.Color(0, 255, 51));
        s68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s68ActionPerformed(evt);
            }
        });
        s9.add(s68);

        s76.setBackground(new java.awt.Color(0, 0, 0));
        s76.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s76.setForeground(new java.awt.Color(0, 255, 51));
        s76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s76ActionPerformed(evt);
            }
        });
        s9.add(s76);

        s77.setBackground(new java.awt.Color(0, 0, 0));
        s77.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s77.setForeground(new java.awt.Color(0, 255, 51));
        s77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s77ActionPerformed(evt);
            }
        });
        s9.add(s77);

        s78.setBackground(new java.awt.Color(0, 0, 0));
        s78.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s78.setForeground(new java.awt.Color(0, 255, 51));
        s78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s78ActionPerformed(evt);
            }
        });
        s9.add(s78);

        s86.setBackground(new java.awt.Color(0, 0, 0));
        s86.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s86.setForeground(new java.awt.Color(0, 255, 51));
        s86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s86ActionPerformed(evt);
            }
        });
        s9.add(s86);

        s87.setBackground(new java.awt.Color(0, 0, 0));
        s87.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s87.setForeground(new java.awt.Color(0, 255, 51));
        s87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s87ActionPerformed(evt);
            }
        });
        s9.add(s87);

        s88.setBackground(new java.awt.Color(0, 0, 0));
        s88.setFont(new java.awt.Font("OCR A Extended", 1, 30)); // NOI18N
        s88.setForeground(new java.awt.Color(0, 255, 51));
        s88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s88ActionPerformed(evt);
            }
        });
        s9.add(s88);

        S.add(s9);

        clean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpia1.png"))); // NOI18N
        clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cleanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cleanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cleanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cleanMouseReleased(evt);
            }
        });

        solve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/solve11.png"))); // NOI18N
        solve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                solveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                solveMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(solve, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solve, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s00ActionPerformed

    private void s01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s01ActionPerformed

    private void s02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s02ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s10ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s11ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s12ActionPerformed

    private void s20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s20ActionPerformed

    private void s21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s21ActionPerformed

    private void s22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s22ActionPerformed

    private void s03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s03ActionPerformed

    private void s04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s04ActionPerformed

    private void s05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s05ActionPerformed

    private void s13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s13ActionPerformed

    private void s14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s14ActionPerformed

    private void s15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s15ActionPerformed

    private void s23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s23ActionPerformed

    private void s24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s24ActionPerformed

    private void s25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s25ActionPerformed

    private void s06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s06ActionPerformed

    private void s07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s07ActionPerformed

    private void s08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s08ActionPerformed

    private void s16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s16ActionPerformed

    private void s17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s17ActionPerformed

    private void s18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s18ActionPerformed

    private void s26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s26ActionPerformed

    private void s27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s27ActionPerformed

    private void s28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s28ActionPerformed

    private void s30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s30ActionPerformed

    private void s31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s31ActionPerformed

    private void s32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s32ActionPerformed

    private void s40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s40ActionPerformed

    private void s41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s41ActionPerformed

    private void s42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s42ActionPerformed

    private void s50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s50ActionPerformed

    private void s51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s51ActionPerformed

    private void s52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s52ActionPerformed

    private void s33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s33ActionPerformed

    private void s34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s34ActionPerformed

    private void s35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s35ActionPerformed

    private void s43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s43ActionPerformed

    private void s44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s44ActionPerformed

    private void s45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s45ActionPerformed

    private void s53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s53ActionPerformed

    private void s54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s54ActionPerformed

    private void s55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s55ActionPerformed

    private void s36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s36ActionPerformed

    private void s37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s37ActionPerformed

    private void s38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s38ActionPerformed

    private void s46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s46ActionPerformed

    private void s47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s47ActionPerformed

    private void s48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s48ActionPerformed

    private void s56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s56ActionPerformed

    private void s57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s57ActionPerformed

    private void s58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s58ActionPerformed

    private void s60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s60ActionPerformed

    private void s61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s61ActionPerformed

    private void s62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s62ActionPerformed

    private void s70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s70ActionPerformed

    private void s71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s71ActionPerformed

    private void s72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s72ActionPerformed

    private void s80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s80ActionPerformed

    private void s81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s81ActionPerformed

    private void s82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s82ActionPerformed

    private void s63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s63ActionPerformed

    private void s64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s64ActionPerformed

    private void s65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s65ActionPerformed

    private void s73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s73ActionPerformed

    private void s74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s74ActionPerformed

    private void s75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s75ActionPerformed

    private void s83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s83ActionPerformed

    private void s84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s84ActionPerformed

    private void s85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s85ActionPerformed

    private void s66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s66ActionPerformed

    private void s67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s67ActionPerformed

    private void s68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s68ActionPerformed

    private void s76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s76ActionPerformed

    private void s77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s77ActionPerformed

    private void s78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s78ActionPerformed

    private void s86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s86ActionPerformed

    private void s87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s87ActionPerformed

    private void s88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s88ActionPerformed

    private void solveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveMouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/solve22.png"));
        
        solve.setIcon(i);
    }//GEN-LAST:event_solveMouseEntered

    private void solveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveMouseExited
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/solve11.png"));
        
        solve.setIcon(i);
    }//GEN-LAST:event_solveMouseExited

    private void solveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/solve33.png"));
        
        solve.setIcon(i);
        
        if(pasarMatriz()){
            if(!Sudoku.sePuedeResolver(matriz))
                 incorrecto(1);
            else{
                Sudoku.pasaMatriz(matriz);
                llenaMatriz();  
             }  
        }
        else
            incorrecto(2);
    }//GEN-LAST:event_solveMousePressed

    private void solveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/solve11.png"));
        
        solve.setIcon(i);
    }//GEN-LAST:event_solveMouseReleased

    private void cleanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/limpia2.png"));
        
        clean.setIcon(i);
    }//GEN-LAST:event_cleanMouseEntered

    private void cleanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseExited
         ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/limpia1.png"));
        
        clean.setIcon(i);
    }//GEN-LAST:event_cleanMouseExited

    private void cleanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMousePressed
        ImageIcon u=new ImageIcon(getClass().getResource("/Recursos/limpia3.png"));
        
        clean.setIcon(u);
        limpiaMatriz();   
    }//GEN-LAST:event_cleanMousePressed

    private void cleanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/limpia1.png"));
        
        clean.setIcon(i);
    }//GEN-LAST:event_cleanMouseReleased
    private void creaMatriz(){   
        matrizT[0][0]=s00;
        matrizT[0][1]=s01;
        matrizT[0][2]=s02;
        matrizT[0][3]=s03;
        matrizT[0][4]=s04;
        matrizT[0][5]=s05;
        matrizT[0][6]=s06;
        matrizT[0][7]=s07;
        matrizT[0][8]=s08;
        matrizT[1][0]=s10;
        matrizT[1][1]=s11;
        matrizT[1][2]=s12;
        matrizT[1][3]=s13;
        matrizT[1][4]=s14;
        matrizT[1][5]=s15;
        matrizT[1][6]=s16;
        matrizT[1][7]=s17;
        matrizT[1][8]=s18;
        matrizT[2][0]=s20;
        matrizT[2][1]=s21;
        matrizT[2][2]=s22;
        matrizT[2][3]=s23;
        matrizT[2][4]=s24;
        matrizT[2][5]=s25;
        matrizT[2][6]=s26;
        matrizT[2][7]=s27;
        matrizT[2][8]=s28;
        matrizT[3][0]=s30;
        matrizT[3][1]=s31;
        matrizT[3][2]=s32;
        matrizT[3][3]=s33;
        matrizT[3][4]=s34;
        matrizT[3][5]=s35;
        matrizT[3][6]=s36;
        matrizT[3][7]=s37;
        matrizT[3][8]=s38;
        matrizT[4][0]=s40;
        matrizT[4][1]=s41;
        matrizT[4][2]=s42;
        matrizT[4][3]=s43;
        matrizT[4][4]=s44;
        matrizT[4][5]=s45;
        matrizT[4][6]=s46;
        matrizT[4][7]=s47;
        matrizT[4][8]=s48;
        matrizT[5][0]=s50;
        matrizT[5][1]=s51;
        matrizT[5][2]=s52;
        matrizT[5][3]=s53;
        matrizT[5][4]=s54;
        matrizT[5][5]=s55;
        matrizT[5][6]=s56;
        matrizT[5][7]=s57;
        matrizT[5][8]=s58;
        matrizT[6][0]=s60;
        matrizT[6][1]=s61;
        matrizT[6][2]=s62;
        matrizT[6][3]=s63;
        matrizT[6][4]=s64;
        matrizT[6][5]=s65;
        matrizT[6][6]=s66;
        matrizT[6][7]=s67;
        matrizT[6][8]=s68;
        matrizT[7][0]=s70;
        matrizT[7][1]=s71;
        matrizT[7][2]=s72;
        matrizT[7][3]=s73;
        matrizT[7][4]=s74;
        matrizT[7][5]=s75;
        matrizT[7][6]=s76;
        matrizT[7][7]=s77;
        matrizT[7][8]=s78;
        matrizT[8][0]=s80;
        matrizT[8][1]=s81;
        matrizT[8][2]=s82;
        matrizT[8][3]=s83;
        matrizT[8][4]=s84;
        matrizT[8][5]=s85;
        matrizT[8][6]=s86;
        matrizT[8][7]=s87;
        matrizT[8][8]=s88;
    }
    private boolean pasarMatriz(){
        String t;
        int num=0;
        boolean res=true;
        
        
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                t=matrizT[i][j].getText();
                if(t.equals("1")||t.equals("2")||t.equals("3")||t.equals("4")||t.equals("5")||t.equals("6")||t.equals("7")||t.equals("8")||t.equals("9")){
                    num=Integer.parseInt(t); 
                    matriz[i][j]=num;
                }   
                else{
                    matriz[i][j]=0;
                    if(res&&!t.equals(""))
                        res=false;
                }
                    
            }
        }
        return res;
    }
    /*private void imprimeMatriz(){
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                System.out.print(matriz[i][j]+" ");   
            }
            System.out.println("");
        }
        System.out.println("");  
    }*/
    private void cambiaRojo(){
        Color color1;

        color1 = Color.RED;
        for(int i=0; i<9; i++)
            for(int j=0; j<9;j++)
                  matrizT[i][j].setForeground(color1);  
   
    }
    private void cambiaAzul(){
        Color color1;

        color1 = Color.CYAN;
        for(int i=0; i<9; i++)
            for(int j=0; j<9;j++)
                  matrizT[i][j].setForeground(color1);  
   
    }
     private void cambiaVerde() {
        Color color2;

        color2 = Color.GREEN;
        for(int i=0; i<9; i++)
            for(int j=0; j<9;j++)
                  matrizT[i][j].setForeground(color2);     
    }
     private void cambiaNegro(){
        Color color;

        color= Color.BLACK;
        for(int i=0; i<9; i++)
            for(int j=0; j<9;j++)
                  matrizT[i][j].setForeground(color);       
     }
     
     private void parpadea(){
        counter=1;
         
        cambiaNegro();
        ActionListener listener = new ActionListener(){
            public void actionPerformed(ActionEvent event){
                int n;
                
                n=counter%2;
                switch(n){
                    case 1:cambiaVerde();
                    break;
                    default:
                    cambiaNegro();      
                }
                counter++;
                if (counter >= 6) {
                    timer.stop();
                    cambiaAzul();
                }
                  
                }    
             };   
         if (timer != null && timer.isRunning()) {
            return;
         }
         timer = new Timer(500, listener);
         timer.start();    
     }
     private void llenaMatriz(){
        ii=0;
        jj=0;
        
        cambiaRojo();
        ActionListener listener = new ActionListener(){
            public void actionPerformed(ActionEvent event){
                matrizT[ii][jj].setText(matriz[ii][jj]+"");
                jj++;
                if(jj>8){
                    jj=0;
                    ii++;
                }
                if (ii >8){
                   timer.stop();
                   parpadea();
                } 
                }    
             };   
         if (timer != null && timer.isRunning()) {
            return;
         }
         timer = new Timer(50, listener);
         timer.start(); 
 
     }
     private void incorrecto(int a){
        cambiaRojo();
        switch(a){
            case 1:
            mensajeSobre();
            break;
            default:
                mensajeError();
        }
        ActionListener listener = new ActionListener(){
            public void actionPerformed(ActionEvent event){
                limpiaMatriz();
                timer.stop();
                }    
             };   
         if (timer != null && timer.isRunning()) {
            return;
         }
         timer = new Timer(2500, listener);
         timer.start(); 
     }
     private void mensajeSobre(){
         cambiaRojo();
         s00.setText("*");
         s01.setText("*");
         s02.setText("*");
         s03.setText("*");
         s04.setText("*");
         s05.setText("*");
         s06.setText("*");
         s07.setText("*");
         s08.setText("*");
         s10.setText("-");
         s11.setText("V");
         s12.setText("A");
         s13.setText("L");
         s14.setText("O");
         s15.setText("R");
         s16.setText("E");
         s17.setText("S");
         s18.setText("-");
         s20.setText("E");
         s21.setText("R");
         s22.setText("R");
         s23.setText("R");
         s24.setText("O");
         s25.setText("N");
         s26.setText("E");
         s27.setText("O");
         s28.setText("S");
         s30.setText("*");
         s31.setText("*");
         s32.setText("*");
         s33.setText("*");
         s34.setText("*");
         s35.setText("*");
         s36.setText("*");
         s37.setText("*");
         s38.setText("*");
         s40.setText("¡");
         s41.setText("P");
         s42.setText("R");
         s43.setText("O");
         s44.setText("B");
         s45.setText("L");
         s46.setText("E");
         s47.setText("M");
         s48.setText("A");
         s50.setText("");
         s51.setText("");
         s52.setText("S");
         s53.setText("O");
         s54.setText("B");
         s55.setText("R");
         s56.setText("E");
         s57.setText("-");
         s58.setText("");
         s60.setText("");
         s61.setText("R");
         s62.setText("E");
         s63.setText("S");
         s64.setText("T");
         s65.setText("R");
         s66.setText("I");
         s67.setText("N");
         s68.setText("-");
         s70.setText("");
         s71.setText("");
         s72.setText("G");
         s73.setText("I");
         s74.setText("D");
         s75.setText("0");
         s76.setText("!");
         s77.setText("");
         s78.setText("");
         s80.setText("*");
         s81.setText("*");
         s82.setText("*");
         s83.setText("*");
         s84.setText("*");
         s85.setText("*");
         s86.setText("*");
         s87.setText("*");
         s88.setText("*");   
     }
     private void mensajeError(){
         cambiaRojo();
         s00.setText("*");
         s01.setText("*");
         s02.setText("*");
         s03.setText("*");
         s04.setText("*");
         s05.setText("*");
         s06.setText("*");
         s07.setText("*");
         s08.setText("*");
         s10.setText("-");
         s11.setText("V");
         s12.setText("A");
         s13.setText("L");
         s14.setText("O");
         s15.setText("R");
         s16.setText("E");
         s17.setText("S");
         s18.setText("-");
         s20.setText("E");
         s21.setText("R");
         s22.setText("R");
         s23.setText("R");
         s24.setText("O");
         s25.setText("N");
         s26.setText("E");
         s27.setText("O");
         s28.setText("S");
         s30.setText("*");
         s31.setText("*");
         s32.setText("*");
         s33.setText("*");
         s34.setText("*");
         s35.setText("*");
         s36.setText("*");
         s37.setText("*");
         s38.setText("*");
         s40.setText("-");
         s41.setText("V");
         s42.setText("A");
         s43.setText("L");
         s44.setText("O");
         s45.setText("R");
         s46.setText("E");
         s47.setText("S");
         s48.setText("-");
         s50.setText("E");
         s51.setText("R");
         s52.setText("R");
         s53.setText("R");
         s54.setText("O");
         s55.setText("N");
         s56.setText("E");
         s57.setText("O");
         s58.setText("S");
         s60.setText("*");
         s61.setText("*");
         s62.setText("*");
         s63.setText("*");
         s64.setText("*");
         s65.setText("*");
         s66.setText("*");
         s67.setText("*");
         s68.setText("*");
         s70.setText("*");
         s71.setText("*");
         s72.setText("*");
         s73.setText("*");
         s74.setText("*");
         s75.setText("*");
         s76.setText("*");
         s77.setText("*");
         s78.setText("*");
         s80.setText("*");
         s81.setText("*");
         s82.setText("*");
         s83.setText("*");
         s84.setText("*");
         s85.setText("*");
         s86.setText("*");
         s87.setText("*");
         s88.setText("*");   
     }
     private void limpiaMatriz(){
         for(int i=0; i<9; i++)
            for(int j=0; j<9;j++)
                  matrizT[i][j].setText("");
        cambiaVerde();
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane S;
    private javax.swing.JLabel clean;
    private javax.swing.JTextField s00;
    private javax.swing.JTextField s01;
    private javax.swing.JTextField s02;
    private javax.swing.JTextField s03;
    private javax.swing.JTextField s04;
    private javax.swing.JTextField s05;
    private javax.swing.JTextField s06;
    private javax.swing.JTextField s07;
    private javax.swing.JTextField s08;
    private javax.swing.JLayeredPane s1;
    private javax.swing.JTextField s10;
    private javax.swing.JTextField s11;
    private javax.swing.JTextField s12;
    private javax.swing.JTextField s13;
    private javax.swing.JTextField s14;
    private javax.swing.JTextField s15;
    private javax.swing.JTextField s16;
    private javax.swing.JTextField s17;
    private javax.swing.JTextField s18;
    private javax.swing.JLayeredPane s2;
    private javax.swing.JTextField s20;
    private javax.swing.JTextField s21;
    private javax.swing.JTextField s22;
    private javax.swing.JTextField s23;
    private javax.swing.JTextField s24;
    private javax.swing.JTextField s25;
    private javax.swing.JTextField s26;
    private javax.swing.JTextField s27;
    private javax.swing.JTextField s28;
    private javax.swing.JLayeredPane s3;
    private javax.swing.JTextField s30;
    private javax.swing.JTextField s31;
    private javax.swing.JTextField s32;
    private javax.swing.JTextField s33;
    private javax.swing.JTextField s34;
    private javax.swing.JTextField s35;
    private javax.swing.JTextField s36;
    private javax.swing.JTextField s37;
    private javax.swing.JTextField s38;
    private javax.swing.JLayeredPane s4;
    private javax.swing.JTextField s40;
    private javax.swing.JTextField s41;
    private javax.swing.JTextField s42;
    private javax.swing.JTextField s43;
    private javax.swing.JTextField s44;
    private javax.swing.JTextField s45;
    private javax.swing.JTextField s46;
    private javax.swing.JTextField s47;
    private javax.swing.JTextField s48;
    private javax.swing.JLayeredPane s5;
    private javax.swing.JTextField s50;
    private javax.swing.JTextField s51;
    private javax.swing.JTextField s52;
    private javax.swing.JTextField s53;
    private javax.swing.JTextField s54;
    private javax.swing.JTextField s55;
    private javax.swing.JTextField s56;
    private javax.swing.JTextField s57;
    private javax.swing.JTextField s58;
    private javax.swing.JLayeredPane s6;
    private javax.swing.JTextField s60;
    private javax.swing.JTextField s61;
    private javax.swing.JTextField s62;
    private javax.swing.JTextField s63;
    private javax.swing.JTextField s64;
    private javax.swing.JTextField s65;
    private javax.swing.JTextField s66;
    private javax.swing.JTextField s67;
    private javax.swing.JTextField s68;
    private javax.swing.JLayeredPane s7;
    private javax.swing.JTextField s70;
    private javax.swing.JTextField s71;
    private javax.swing.JTextField s72;
    private javax.swing.JTextField s73;
    private javax.swing.JTextField s74;
    private javax.swing.JTextField s75;
    private javax.swing.JTextField s76;
    private javax.swing.JTextField s77;
    private javax.swing.JTextField s78;
    private javax.swing.JLayeredPane s8;
    private javax.swing.JTextField s80;
    private javax.swing.JTextField s81;
    private javax.swing.JTextField s82;
    private javax.swing.JTextField s83;
    private javax.swing.JTextField s84;
    private javax.swing.JTextField s85;
    private javax.swing.JTextField s86;
    private javax.swing.JTextField s87;
    private javax.swing.JTextField s88;
    private javax.swing.JLayeredPane s9;
    private javax.swing.JLabel solve;
    // End of variables declaration//GEN-END:variables
}
