
package calculadora;

import javax.swing.ImageIcon;

public class CalculadoraVista extends javax.swing.JFrame {
    private StringBuilder b;
    private boolean oper;
    private boolean syn;

    public CalculadoraVista() {
        initComponents();
        b=new StringBuilder();
        oper=true;
        syn=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b0 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        bMas = new javax.swing.JLabel();
        bMen = new javax.swing.JLabel();
        bPun = new javax.swing.JLabel();
        bPor = new javax.swing.JLabel();
        bAC = new javax.swing.JLabel();
        bPd = new javax.swing.JLabel();
        bDiv = new javax.swing.JLabel();
        bPi = new javax.swing.JLabel();
        bI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        b1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b1.png"))); // NOI18N
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b1MouseReleased(evt);
            }
        });

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b3.png"))); // NOI18N
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b3MouseReleased(evt);
            }
        });

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b2.png"))); // NOI18N
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b2MouseReleased(evt);
            }
        });

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b4.png"))); // NOI18N
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b4MouseReleased(evt);
            }
        });

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b5.png"))); // NOI18N
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b5MouseReleased(evt);
            }
        });

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b6.png"))); // NOI18N
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b6MouseReleased(evt);
            }
        });

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b7.png"))); // NOI18N
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b7MouseReleased(evt);
            }
        });

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b8.png"))); // NOI18N
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b8MouseReleased(evt);
            }
        });

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b9.png"))); // NOI18N
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b9MouseReleased(evt);
            }
        });

        b0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b0.png"))); // NOI18N
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b0MouseReleased(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        bMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b+.png"))); // NOI18N
        bMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bMasMouseReleased(evt);
            }
        });

        bMen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/b-.png"))); // NOI18N
        bMen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bMenMouseReleased(evt);
            }
        });

        bPun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bp.png"))); // NOI18N
        bPun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPunMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPunMouseReleased(evt);
            }
        });

        bPor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bpo.png"))); // NOI18N
        bPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPorMouseReleased(evt);
            }
        });

        bAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bac.png"))); // NOI18N
        bAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bACMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bACMouseReleased(evt);
            }
        });

        bPd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bpd.png"))); // NOI18N
        bPd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPdMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPdMouseReleased(evt);
            }
        });

        bDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bdd.png"))); // NOI18N
        bDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bDivMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bDivMouseReleased(evt);
            }
        });

        bPi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bpi.png"))); // NOI18N
        bPi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPiMouseReleased(evt);
            }
        });

        bI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bi.png"))); // NOI18N
        bI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bIMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bPi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bPd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bPun, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bMen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bPor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bPun, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bAC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bPi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bPor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bMas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b11.png"));
        
        b1.setIcon(i);
    }//GEN-LAST:event_b1MouseEntered

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b22.png"));
        
        b2.setIcon(i);     
    }//GEN-LAST:event_b2MouseEntered

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b33.png"));
         
        b3.setIcon(i);    
    }//GEN-LAST:event_b3MouseEntered

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
         ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b44.png"));
         
         b4.setIcon(i);      
    }//GEN-LAST:event_b4MouseEntered

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b55.png"));
        
        b5.setIcon(i);       
    }//GEN-LAST:event_b5MouseEntered

    private void b6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b66.png"));
        
        b6.setIcon(i);   
    }//GEN-LAST:event_b6MouseEntered

    private void b7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b77.png"));
        
        b7.setIcon(i);    
    }//GEN-LAST:event_b7MouseEntered

    private void b8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b88.png"));
        
        b8.setIcon(i);     
    }//GEN-LAST:event_b8MouseEntered

    private void b9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b99.png"));
        
        b9.setIcon(i);       
    }//GEN-LAST:event_b9MouseEntered

    private void b0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseEntered
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b00.png"));
        
        b0.setIcon(i);        
    }//GEN-LAST:event_b0MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b1.png"));
       
        b1.setIcon(i);     
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b2.png"));
        
        b2.setIcon(i);               
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b3.png"));
        
        b3.setIcon(i);          
    }//GEN-LAST:event_b3MouseExited

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b4.png"));
        
        b4.setIcon(i);          
    }//GEN-LAST:event_b4MouseExited

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b5.png"));
        
        b5.setIcon(i);           
    }//GEN-LAST:event_b5MouseExited

    private void b6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b6.png"));
        
        b6.setIcon(i);          
    }//GEN-LAST:event_b6MouseExited

    private void b7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b7.png"));
        
        b7.setIcon(i);          
    }//GEN-LAST:event_b7MouseExited

    private void b8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b8.png"));
        
        b8.setIcon(i);           
    }//GEN-LAST:event_b8MouseExited

    private void b9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseExited
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b9.png"));
        
        b9.setIcon(i);         
    }//GEN-LAST:event_b9MouseExited

    private void b1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MousePressed
    ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b111.png"));
    
    b1.setIcon(i);
    if(!oper||!syn)
        borra();
        
     b.append("1");
     t1.setText(b.toString());  
    }//GEN-LAST:event_b1MousePressed

    private void b1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b1.png"));
        
        b1.setIcon(i);  
    }//GEN-LAST:event_b1MouseReleased

    private void b0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseExited
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b0.png"));
       
        b0.setIcon(i); 
    }//GEN-LAST:event_b0MouseExited

    private void b2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b222.png"));
        
        b2.setIcon(i);  
        if(!oper||!syn)
            borra();
        b.append("2");
        t1.setText(b.toString()); 
    }//GEN-LAST:event_b2MousePressed

    private void b3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b333.png"));
        
        b3.setIcon(i);
        if(!oper||!syn)
            borra();
        b.append("3");
        t1.setText(b.toString());
    }//GEN-LAST:event_b3MousePressed

    private void b4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b444.png"));
        
        b4.setIcon(i); 
        if(!oper||!syn)
            borra();
        b.append("4");
        t1.setText(b.toString());
    }//GEN-LAST:event_b4MousePressed

    private void b5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b555.png"));
        
        b5.setIcon(i);  
        if(!oper||!syn)
            borra();
         b.append("5");
         t1.setText(b.toString());       
    }//GEN-LAST:event_b5MousePressed

    private void b6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b666.png"));
        
        b6.setIcon(i);   
        if(!oper||!syn)
            borra();
        b.append("6");
        t1.setText(b.toString());  
    }//GEN-LAST:event_b6MousePressed

    private void b7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b777.png"));
        
        b7.setIcon(i); 
        if(!oper||!syn)
            borra();
        b.append("7");
        t1.setText(b.toString());
    }//GEN-LAST:event_b7MousePressed

    private void b8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b888.png"));
        
        b8.setIcon(i);  
        if(!oper||!syn)
            borra();
        b.append("8");
        t1.setText(b.toString());
    }//GEN-LAST:event_b8MousePressed

    private void b9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b999.png"));
        
        b9.setIcon(i); 
        if(!oper||!syn)
            borra();
        b.append("9");
        t1.setText(b.toString());   
    }//GEN-LAST:event_b9MousePressed

    private void b0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b000.png"));
        
        b0.setIcon(i);   
        if(!oper||!syn)
            borra();
        b.append("0");
        t1.setText(b.toString());//         
    }//GEN-LAST:event_b0MousePressed

    private void b2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b2.png"));
        
        b2.setIcon(i);           
    }//GEN-LAST:event_b2MouseReleased

    private void b3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b3.png"));
        
        b3.setIcon(i);         
    }//GEN-LAST:event_b3MouseReleased

    private void b4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b4.png"));
        
        b4.setIcon(i);     
    }//GEN-LAST:event_b4MouseReleased

    private void b5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b5.png"));
        
        b5.setIcon(i);    
    }//GEN-LAST:event_b5MouseReleased

    private void b6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b6.png"));
        
        b6.setIcon(i);           
    }//GEN-LAST:event_b6MouseReleased

    private void b7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b7.png"));
        
        b7.setIcon(i);         
    }//GEN-LAST:event_b7MouseReleased

    private void b8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b8.png"));
        
        b8.setIcon(i);      
    }//GEN-LAST:event_b8MouseReleased

    private void b9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b9.png"));
        
        b9.setIcon(i);           
    }//GEN-LAST:event_b9MouseReleased

    private void b0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b0.png"));
        
        b0.setIcon(i);           
    }//GEN-LAST:event_b0MouseReleased

    private void bMasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMasMousePressed
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b++.png"));
       
        bMas.setIcon(i);
        oper=true;
        if(!syn)
            borra();
        b.append("+");
        t1.setText(b.toString());
    }//GEN-LAST:event_bMasMousePressed

    private void bMasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMasMouseReleased
         ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b+.png"));
         
         bMas.setIcon(i);   
    }//GEN-LAST:event_bMasMouseReleased

    private void bDivMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDivMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bdd.png"));
 
        bDiv.setIcon(i);   
    }//GEN-LAST:event_bDivMouseReleased

    private void bPorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPorMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpo.png"));
        
        bPor.setIcon(i);  
    }//GEN-LAST:event_bPorMouseReleased

    private void bMenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b-.png"));
        
        bMen.setIcon(i);   
    }//GEN-LAST:event_bMenMouseReleased

    private void bPunMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPunMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bp.png"));
        
        bPun.setIcon(i);   
    }//GEN-LAST:event_bPunMouseReleased

    private void bPiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPiMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpi.png"));
        
        bPi.setIcon(i);   
    }//GEN-LAST:event_bPiMouseReleased

    private void bPdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpd.png"));
        
        bPd.setIcon(i);   
    }//GEN-LAST:event_bPdMouseReleased

    private void bACMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bACMouseReleased
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bac.png"));
       
        bAC.setIcon(i);  
    }//GEN-LAST:event_bACMouseReleased

    private void bIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIMouseReleased
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bi.png"));
        
        bI.setIcon(i);  
    }//GEN-LAST:event_bIMouseReleased

    private void bDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDivMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bd.png"));
        
        bDiv.setIcon(i);
        oper=true;
        if(!syn)
            borra();
        b.append("/");
       t1.setText(b.toString());
    }//GEN-LAST:event_bDivMousePressed

    private void bPorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPorMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpor.png"));
        
        bPor.setIcon(i);
        oper=true;
        if(!syn)
            borra();
        b.append("*");
        t1.setText(b.toString());
    }//GEN-LAST:event_bPorMousePressed

    private void bMenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/b--.png"));
        
        bMen.setIcon(i); 
        oper=true;
        if(!syn)
            borra();
        b.append("-");
        t1.setText(b.toString());
    }//GEN-LAST:event_bMenMousePressed

    private void bPunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPunMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpp.png"));
        
        bPun.setIcon(i);
        oper=true;
        if(!syn)
            borra();
        b.append(".");
        t1.setText(b.toString());
    }//GEN-LAST:event_bPunMousePressed

    private void bIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bii.png"));
        String res;
        
        bI.setIcon(i);
      
        if(!b.toString().isEmpty()){
            if(Calculadora.revisaTodo(b.toString())){
                res=Calculadora.eliminarExcesos(b.toString());
                res=Calculadora.convertirPostfijo(res);
                b.setLength(0);
                b.append(Calculadora.evaluarPostfijo(res));
                t1.setText(b.toString());
                oper=false;
            }  
            else{
                b.setLength(0);
                b.append("Syntax Error");
                t1.setText(b.toString());   
                oper=false;
                syn=false;
            }
        }
    }//GEN-LAST:event_bIMousePressed

    private void bPiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPiMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpai.png"));
        
        bPi.setIcon(i);
        oper=true;
        if(!syn)
            borra();
        b.append("(");
        t1.setText(b.toString());
    }//GEN-LAST:event_bPiMousePressed

    private void bPdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPdMousePressed
       ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bpdd.png"));
       
        bPd.setIcon(i); 
        oper=true;
        if(!syn)
            borra();
        b.append(")");
        t1.setText(b.toString());
    }//GEN-LAST:event_bPdMousePressed

    private void bACMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bACMousePressed
        ImageIcon i=new ImageIcon(getClass().getResource("/Recursos/bacc.png"));
        
         bAC.setIcon(i); 
         borra();
    }//GEN-LAST:event_bACMousePressed
    private void borra(){
        b.setLength(0);
        t1.setText(b.toString());
        oper=true;
        syn=true;
    }

    public static void main(String args[]) {
     

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b0;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JLabel bAC;
    private javax.swing.JLabel bDiv;
    private javax.swing.JLabel bI;
    private javax.swing.JLabel bMas;
    private javax.swing.JLabel bMen;
    private javax.swing.JLabel bPd;
    private javax.swing.JLabel bPi;
    private javax.swing.JLabel bPor;
    private javax.swing.JLabel bPun;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
